---
- hosts: cyber_range
  become: true
  roles:
    - cyber_range_setup
    - logging

- hosts: trainee_workstation
  become: true
  roles:
    - role: common_bootstrap
      vars:
        common_bootstrap_install_docker: true
    - bips
    - logging

- hosts: training_platform
  become: true
  roles:
    - role: common_bootstrap
      vars:
        common_bootstrap_install_docker: true
    - cicms

- hosts: ng_siem
  become: true
  roles:
    - role: common_bootstrap
      vars:
        common_bootstrap_install_docker: true
    - ng_siem

- hosts: ng_soar
  become: true
  roles:
    - role: common_bootstrap
      vars:
        common_bootstrap_install_docker: true
    - ng_soar
