# Generated by scripts/generate_deploy_tf.py; do not edit manually.

resource "openstack_networking_network_v2" "training_net" {
  name = "training-net"
}

resource "openstack_networking_subnet_v2" "training_net_subnet" {
  name       = "training-net-subnet"
  network_id = openstack_networking_network_v2.training_net.id
  cidr       = "10.10.0.0/24"
  gateway_ip = "10.10.0.1"
  enable_dhcp = true
  allocation_pool {
    start = "10.10.0.20"
    end   = "10.10.0.199"
  }
}

resource "openstack_networking_port_v2" "training_platform_training_net" {
  name       = "training-platform-training-net-port"
  network_id = openstack_networking_network_v2.training_net.id
  fixed_ip {
    ip_address = "10.10.0.200"
  }
}

resource "openstack_networking_port_v2" "trainee_workstation_training_net" {
  name       = "trainee-workstation-training-net-port"
  network_id = openstack_networking_network_v2.training_net.id
  fixed_ip {
    ip_address = "10.10.0.201"
  }
}

resource "openstack_networking_port_v2" "cyber_range_training_net" {
  name       = "cyber-range-training-net-port"
  network_id = openstack_networking_network_v2.training_net.id
  fixed_ip {
    ip_address = "10.10.0.202"
  }
}

resource "openstack_networking_port_v2" "randomization_platform_training_net" {
  name       = "randomization-platform-training-net-port"
  network_id = openstack_networking_network_v2.training_net.id
  fixed_ip {
    ip_address = "10.10.0.203"
  }
}

resource "openstack_networking_port_v2" "bips_training_net" {
  name       = "bips-training-net-port"
  network_id = openstack_networking_network_v2.training_net.id
  fixed_ip {
    ip_address = "10.10.0.204"
  }
}

resource "openstack_networking_port_v2" "ng_siem_training_net" {
  name       = "ng-siem-training-net-port"
  network_id = openstack_networking_network_v2.training_net.id
  fixed_ip {
    ip_address = "10.10.0.205"
  }
}

resource "openstack_networking_port_v2" "cicms_training_net" {
  name       = "cicms-training-net-port"
  network_id = openstack_networking_network_v2.training_net.id
  fixed_ip {
    ip_address = "10.10.0.206"
  }
}

resource "openstack_networking_port_v2" "ng_soar_training_net" {
  name       = "ng-soar-training-net-port"
  network_id = openstack_networking_network_v2.training_net.id
  fixed_ip {
    ip_address = "10.10.0.207"
  }
}

resource "openstack_compute_instance_v2" "training_platform" {
  name = "training-platform"

  network {
    port = openstack_networking_port_v2.training_platform_training_net.id
  }

  depends_on = [
    openstack_networking_subnet_v2.training_net_subnet,
    openstack_networking_port_v2.training_platform_training_net,
  ]
}

resource "openstack_compute_instance_v2" "trainee_workstation" {
  name = "trainee-workstation"

  network {
    port = openstack_networking_port_v2.trainee_workstation_training_net.id
  }

  depends_on = [
    openstack_networking_subnet_v2.training_net_subnet,
    openstack_networking_port_v2.trainee_workstation_training_net,
  ]
}

resource "openstack_compute_instance_v2" "cyber_range" {
  name = "cyber-range"

  network {
    port = openstack_networking_port_v2.cyber_range_training_net.id
  }

  depends_on = [
    openstack_networking_subnet_v2.training_net_subnet,
    openstack_networking_port_v2.cyber_range_training_net,
  ]
}

resource "openstack_compute_instance_v2" "randomization_platform" {
  name = "randomization-platform"

  network {
    port = openstack_networking_port_v2.randomization_platform_training_net.id
  }

  depends_on = [
    openstack_networking_subnet_v2.training_net_subnet,
    openstack_networking_port_v2.randomization_platform_training_net,
  ]
}

resource "openstack_compute_instance_v2" "bips" {
  name = "bips"

  network {
    port = openstack_networking_port_v2.bips_training_net.id
  }

  depends_on = [
    openstack_networking_subnet_v2.training_net_subnet,
    openstack_networking_port_v2.bips_training_net,
  ]
}

resource "openstack_compute_instance_v2" "ng_siem" {
  name = "ng-siem"

  network {
    port = openstack_networking_port_v2.ng_siem_training_net.id
  }

  depends_on = [
    openstack_networking_subnet_v2.training_net_subnet,
    openstack_networking_port_v2.ng_siem_training_net,
  ]
}

resource "openstack_compute_instance_v2" "cicms" {
  name = "cicms"

  network {
    port = openstack_networking_port_v2.cicms_training_net.id
  }

  depends_on = [
    openstack_networking_subnet_v2.training_net_subnet,
    openstack_networking_port_v2.cicms_training_net,
  ]
}

resource "openstack_compute_instance_v2" "ng_soar" {
  name = "ng-soar"

  network {
    port = openstack_networking_port_v2.ng_soar_training_net.id
  }

  depends_on = [
    openstack_networking_subnet_v2.training_net_subnet,
    openstack_networking_port_v2.ng_soar_training_net,
  ]
}
