# Generated by scripts/generate_deploy_tf.py; do not edit manually.

resource "openstack_networking_network_v2" "training_net" {
  name = "training-net"
}

resource "openstack_networking_port_v2" "training_platform_training_net" {
  name       = "training-platform-training-net-port"
  network_id = openstack_networking_network_v2.training_net.id
  fixed_ip {
    ip_address = "10.10.0.2"
  }
}

resource "openstack_networking_port_v2" "trainee_workstation_training_net" {
  name       = "trainee-workstation-training-net-port"
  network_id = openstack_networking_network_v2.training_net.id
  fixed_ip {
    ip_address = "10.10.0.3"
  }
}

resource "openstack_networking_port_v2" "cyber_range_training_net" {
  name       = "cyber-range-training-net-port"
  network_id = openstack_networking_network_v2.training_net.id
  fixed_ip {
    ip_address = "10.10.0.4"
  }
}

resource "openstack_networking_port_v2" "randomization_platform_training_net" {
  name       = "randomization-platform-training-net-port"
  network_id = openstack_networking_network_v2.training_net.id
  fixed_ip {
    ip_address = "10.10.0.5"
  }
}

resource "openstack_networking_port_v2" "bips_training_net" {
  name       = "bips-training-net-port"
  network_id = openstack_networking_network_v2.training_net.id
  fixed_ip {
    ip_address = "10.10.0.6"
  }
}

resource "openstack_networking_port_v2" "ng_siem_training_net" {
  name       = "ng-siem-training-net-port"
  network_id = openstack_networking_network_v2.training_net.id
  fixed_ip {
    ip_address = "10.10.0.7"
  }
}

resource "openstack_networking_port_v2" "cicms_training_net" {
  name       = "cicms-training-net-port"
  network_id = openstack_networking_network_v2.training_net.id
  fixed_ip {
    ip_address = "10.10.0.8"
  }
}

resource "openstack_networking_port_v2" "ng_soar_training_net" {
  name       = "ng-soar-training-net-port"
  network_id = openstack_networking_network_v2.training_net.id
  fixed_ip {
    ip_address = "10.10.0.9"
  }
}

resource "openstack_compute_instance_v2" "training_platform" {
  name = "training-platform"

  network {
    port = openstack_networking_port_v2.training_platform_training_net.id
  }

  depends_on = [
    openstack_networking_port_v2.training_platform_training_net,
  ]
}

resource "openstack_compute_instance_v2" "trainee_workstation" {
  name = "trainee-workstation"

  network {
    port = openstack_networking_port_v2.trainee_workstation_training_net.id
  }

  depends_on = [
    openstack_networking_port_v2.trainee_workstation_training_net,
  ]
}

resource "openstack_compute_instance_v2" "cyber_range" {
  name = "cyber-range"

  network {
    port = openstack_networking_port_v2.cyber_range_training_net.id
  }

  depends_on = [
    openstack_networking_port_v2.cyber_range_training_net,
  ]
}

resource "openstack_compute_instance_v2" "randomization_platform" {
  name = "randomization-platform"

  network {
    port = openstack_networking_port_v2.randomization_platform_training_net.id
  }

  depends_on = [
    openstack_networking_port_v2.randomization_platform_training_net,
  ]
}

resource "openstack_compute_instance_v2" "bips" {
  name = "bips"

  network {
    port = openstack_networking_port_v2.bips_training_net.id
  }

  depends_on = [
    openstack_networking_port_v2.bips_training_net,
  ]
}

resource "openstack_compute_instance_v2" "ng_siem" {
  name = "ng-siem"

  network {
    port = openstack_networking_port_v2.ng_siem_training_net.id
  }

  depends_on = [
    openstack_networking_port_v2.ng_siem_training_net,
  ]
}

resource "openstack_compute_instance_v2" "cicms" {
  name = "cicms"

  network {
    port = openstack_networking_port_v2.cicms_training_net.id
  }

  depends_on = [
    openstack_networking_port_v2.cicms_training_net,
  ]
}

resource "openstack_compute_instance_v2" "ng_soar" {
  name = "ng-soar"

  network {
    port = openstack_networking_port_v2.ng_soar_training_net.id
  }

  depends_on = [
    openstack_networking_port_v2.ng_soar_training_net,
  ]
}
