#!/usr/bin/env python3
"""Generate deploy.tf from topology YAML definitions.

Supports both schemas used in this repository:
- topology.yml (hosts list + net_mappings)
- sandboxes/topology_subcase_1b.yaml (hosts dict + interfaces)
"""

from __future__ import annotations

from collections import OrderedDict
from pathlib import Path
import argparse
import yaml


def normalize_name(name: str) -> str:
    return name.replace("-", "_")


def parse_topology(path: Path) -> tuple[list[dict], OrderedDict[str, str]]:
    data = yaml.safe_load(path.read_text())

    hosts: list[dict] = []
    fixed_ips: OrderedDict[str, str] = OrderedDict()

    if isinstance(data.get("hosts"), list):
        # topology.yml schema
        hosts = [{"name": h["name"]} for h in data.get("hosts", [])]
        mappings = data.get("net_mappings", [])
        for m in mappings:
            if m.get("network") == "training-net" and m.get("ip"):
                fixed_ips[m["host"]] = m["ip"]
    else:
        # sandboxes/topology_subcase_1b.yaml schema
        hosts = [{"name": name} for name in data.get("hosts", {}).keys()]
        for host_name, host_data in data.get("hosts", {}).items():
            for interface in host_data.get("interfaces", []):
                if interface.get("network") == "training-net" and interface.get("ip"):
                    fixed_ips[host_name] = interface["ip"]

    return hosts, fixed_ips


def render(topology_file: Path) -> str:
    hosts, fixed_ips = parse_topology(topology_file)

    lines: list[str] = []
    lines.append('# Generated by scripts/generate_deploy_tf.py; do not edit manually.')
    lines.append('')
    lines.append('resource "openstack_networking_network_v2" "training_net" {')
    lines.append('  name = "training-net"')
    lines.append('}')
    lines.append('')

    # Dedicated fixed-IP ports for training-net hosts.
    for host, ip in fixed_ips.items():
        if ip in {f"10.10.0.{n}" for n in range(2, 10)}:
            res = normalize_name(host)
            lines.append(f'resource "openstack_networking_port_v2" "{res}_training_net" {{')
            lines.append(f'  name       = "{host}-training-net-port"')
            lines.append('  network_id = openstack_networking_network_v2.training_net.id')
            lines.append('  fixed_ip {')
            lines.append(f'    ip_address = "{ip}"')
            lines.append('  }')
            lines.append('}')
            lines.append('')

    for host in hosts:
        name = host["name"]
        res = normalize_name(name)
        lines.append(f'resource "openstack_compute_instance_v2" "{res}" {{')
        lines.append(f'  name = "{name}"')
        lines.append('')
        if name in fixed_ips and fixed_ips[name] in {f"10.10.0.{n}" for n in range(2, 10)}:
            lines.append('  network {')
            lines.append(f'    port = openstack_networking_port_v2.{res}_training_net.id')
            lines.append('  }')
            lines.append('')
            lines.append('  depends_on = [')
            lines.append(f'    openstack_networking_port_v2.{res}_training_net,')
            lines.append('  ]')
        else:
            lines.append('  network {')
            lines.append('    uuid = openstack_networking_network_v2.training_net.id')
            lines.append('  }')
        lines.append('}')
        lines.append('')

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--topology", default="topology.yml")
    parser.add_argument("--output", default="deploy.tf")
    args = parser.parse_args()

    topology_file = Path(args.topology)
    output_file = Path(args.output)

    rendered = render(topology_file)
    output_file.write_text(rendered)
    print(f"Wrote {output_file} from {topology_file}")


if __name__ == "__main__":
    main()
