#!/usr/bin/env python3
"""Generate deploy.tf from topology YAML definitions.

Supports both schemas used in this repository:
- topology.yml (hosts list + net_mappings)
- sandboxes/topology_subcase_1b.yaml (hosts dict + interfaces)
"""

from __future__ import annotations

from collections import OrderedDict
from pathlib import Path
import argparse
import yaml


def normalize_name(name: str) -> str:
    return name.replace("-", "_")


def parse_topology(path: Path) -> tuple[list[dict], OrderedDict[str, str], dict]:
    data = yaml.safe_load(path.read_text())

    hosts: list[dict] = []
    fixed_ips: OrderedDict[str, str] = OrderedDict()

    subnet_cfg: dict = {
        "cidr": "10.10.0.0/24",
        "gateway_ip": "10.10.0.1",
        "allocation_pool_start": "10.10.0.20",
        "allocation_pool_end": "10.10.0.199",
    }

    if isinstance(data.get("hosts"), list):
        # topology.yml schema
        hosts = [{"name": h["name"]} for h in data.get("hosts", [])]
        mappings = data.get("net_mappings", [])
        for m in mappings:
            if m.get("network") == "training-net" and m.get("ip"):
                fixed_ips[m["host"]] = m["ip"]
        training_net = next(
            (n for n in data.get("networks", []) if n.get("name") == "training-net"),
            {},
        )
        if training_net:
            subnet_cfg["cidr"] = training_net.get("cidr", subnet_cfg["cidr"])
            subnet_cfg["gateway_ip"] = training_net.get("gateway_ip", subnet_cfg["gateway_ip"])
            pool = training_net.get("allocation_pool", {})
            subnet_cfg["allocation_pool_start"] = pool.get(
                "start", subnet_cfg["allocation_pool_start"]
            )
            subnet_cfg["allocation_pool_end"] = pool.get("end", subnet_cfg["allocation_pool_end"])
    else:
        # sandboxes/topology_subcase_1b.yaml schema
        hosts = [{"name": name} for name in data.get("hosts", {}).keys()]
        for host_name, host_data in data.get("hosts", {}).items():
            for interface in host_data.get("interfaces", []):
                if interface.get("network") == "training-net" and interface.get("ip"):
                    fixed_ips[host_name] = interface["ip"]
        training_net = data.get("networks", {}).get("training-net", {})
        if training_net:
            subnet_cfg["cidr"] = training_net.get("prefix", subnet_cfg["cidr"])
            subnet_cfg["gateway_ip"] = training_net.get("gateway_ip", subnet_cfg["gateway_ip"])
            pool = training_net.get("allocation_pool", {})
            subnet_cfg["allocation_pool_start"] = pool.get(
                "start", subnet_cfg["allocation_pool_start"]
            )
            subnet_cfg["allocation_pool_end"] = pool.get("end", subnet_cfg["allocation_pool_end"])

    return hosts, fixed_ips, subnet_cfg


def render(topology_file: Path) -> str:
    hosts, fixed_ips, subnet_cfg = parse_topology(topology_file)

    lines: list[str] = []
    lines.append('# Generated by scripts/generate_deploy_tf.py; do not edit manually.')
    lines.append('')
    lines.append('resource "openstack_networking_network_v2" "training_net" {')
    lines.append('  name = "training-net"')
    lines.append('}')
    lines.append('')
    lines.append('resource "openstack_networking_subnet_v2" "training_net_subnet" {')
    lines.append('  name       = "training-net-subnet"')
    lines.append('  network_id = openstack_networking_network_v2.training_net.id')
    lines.append(f'  cidr       = "{subnet_cfg["cidr"]}"')
    lines.append(f'  gateway_ip = "{subnet_cfg["gateway_ip"]}"')
    lines.append('  enable_dhcp = true')
    lines.append('  allocation_pool {')
    lines.append(f'    start = "{subnet_cfg["allocation_pool_start"]}"')
    lines.append(f'    end   = "{subnet_cfg["allocation_pool_end"]}"')
    lines.append('  }')
    lines.append('}')
    lines.append('')

    # Dedicated fixed-IP ports for training-net hosts.
    for host, ip in fixed_ips.items():
        res = normalize_name(host)
        lines.append(f'resource "openstack_networking_port_v2" "{res}_training_net" {{')
        lines.append(f'  name       = "{host}-training-net-port"')
        lines.append('  network_id = openstack_networking_network_v2.training_net.id')
        lines.append('  fixed_ip {')
        lines.append(f'    ip_address = "{ip}"')
        lines.append('  }')
        lines.append('}')
        lines.append('')

    for host in hosts:
        name = host["name"]
        res = normalize_name(name)
        lines.append(f'resource "openstack_compute_instance_v2" "{res}" {{')
        lines.append(f'  name = "{name}"')
        lines.append('')
        if name in fixed_ips:
            lines.append('  network {')
            lines.append(f'    port = openstack_networking_port_v2.{res}_training_net.id')
            lines.append('  }')
            lines.append('')
            lines.append('  depends_on = [')
            lines.append('    openstack_networking_subnet_v2.training_net_subnet,')
            lines.append(f'    openstack_networking_port_v2.{res}_training_net,')
            lines.append('  ]')
        else:
            lines.append('  network {')
            lines.append('    uuid = openstack_networking_network_v2.training_net.id')
            lines.append('  }')
            lines.append('')
            lines.append('  depends_on = [')
            lines.append('    openstack_networking_subnet_v2.training_net_subnet,')
            lines.append('  ]')
        lines.append('}')
        lines.append('')

    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--topology", default="topology.yml")
    parser.add_argument("--output", default="deploy.tf")
    args = parser.parse_args()

    topology_file = Path(args.topology)
    output_file = Path(args.output)

    rendered = render(topology_file)
    output_file.write_text(rendered)
    print(f"Wrote {output_file} from {topology_file}")


if __name__ == "__main__":
    main()
