---
- hosts: all
  become: true
  roles:
    - logging


- hosts: training_platform
  become: true
  roles:
    - training_platform


- hosts: trainee_workstation
  become: true
  roles:
    - trainee_workstation

- hosts: cyber_range
  become: true
  roles:
    - cyber_range_setup

- hosts: bips
  become: true
  roles:
    - role: common_bootstrap
      vars:
        common_bootstrap_install_docker: true
    - bips

- hosts: cicms
  become: true
  roles:
    - role: common_bootstrap
      vars:
        common_bootstrap_install_docker: true
    - cicms

- hosts: ng_siem
  become: true
  roles:
    - role: common_bootstrap
      vars:
        common_bootstrap_install_docker: true
    - ng_siem

- hosts: ng_soar
  become: true
  roles:
    - role: common_bootstrap
      vars:
        common_bootstrap_install_docker: true
    - ng_soar
