---
- hosts: all
  become: true
  roles:
    - logging

- hosts: cyber_range
  become: true
  roles:
    - cyber_range_setup

- hosts: bips
  become: true
  roles:
    - bips

- hosts: cicms
  become: true
  roles:
    - cicms

- hosts: ng_siem
  become: true
  roles:
    - ng_siem

- hosts: ng_soar
  become: true
  roles:
    - ng_soar
