---
- name: reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true
  when: randomization_platform_manage_systemd

- name: restart randomization platform service
  ansible.builtin.systemd:
    name: "{{ randomization_platform_service_name }}"
    state: restarted
  when: randomization_platform_manage_systemd
